from __future__ import annotations

from app.services.dashboard.summary import DashboardSummary, DashboardSummaryService
from app.services.portfolio.sync import PortfolioState
from app.services.recovery.orchestrator import BootState


def test_dashboard_summary_service_builds_summary_from_boot_state() -> None:
    service = DashboardSummaryService()
    boot_state = BootState(
        safe_mode=True,
        hard_stop=True,
        trading_ready=False,
        failure_stage="open_order_reconcile",
        portfolio_state=PortfolioState(
            cash_balance=250000.0,
            asset_currency="XRP",
            asset_balance=180.5,
            avg_buy_price=815.0,
        ),
        reconcile_result={"open_order_count": 2},
    )

    summary = service.build(
        boot_state=boot_state,
        trading_mode="demo",
        learning_enabled=True,
        realized_pnl=12500.0,
        unrealized_pnl=-3200.0,
        buy_count=4,
        sell_count=3,
        stop_loss_count=1,
        recent_stop_loss_reason="STOP_LOSS_PRICE_HIT",
        last_learning_event=None,
        learning_signal_count=0,
        learning_fill_count=0,
        last_signal_recorded_at=None,
        last_fill_recorded_at=None,
        last_position_event=None,
        last_promotion_reviewed_at=None,
        last_restart_detected_at=None,
        last_recovery_completed_at=None,
        promotion_ready=False,
        sections=[
            {
                "key": "trading",
                "name": "Trading",
                "state_label": "STOP_LOSS_TRIGGERED",
                "severity": "critical",
                "state_message": "최근 손절 사유: STOP_LOSS_PRICE_HIT",
                "recommended_action": "최근 손절 발생 원인과 청산 흐름을 점검하세요.",
                "updated_at": None,
                "stale": True,
                "age_sec": None,
                "freshness_state": "missing",
                "freshness_message": "데이터 없음",
                "freshness_label": "MISSING",
                "freshness_recommended_action": "데이터 소스와 수집 경로를 확인하세요.",
                "freshness_severity": "warning",
                "freshness_window_sec": 300,
                "freshness_metric_items": [
                    {"key": "updated_at", "label": "Updated At", "type": "timestamp", "state_message": 'Updated At 2026-04-19T20:00:01+09:00', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.market", "value": "2026-04-19T20:00:01+09:00"},
                    {"key": "age_sec", "label": "Age Seconds", "type": "duration_sec", "state_message": 'Age Seconds 299', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.market", "value": 299},
                    {"key": "freshness_window_sec", "label": "Freshness Window Seconds", "type": "window_sec", "state_message": 'Freshness Window Seconds 300', "recommended_action": 'freshness 기준 시간을 참고해 데이터 지연 여부를 판단하세요.', "recommended_action_label": 'REFERENCE_FRESHNESS_WINDOW', "action_group": 'reference', "action_priority": 'medium', "actionable": False, "action_url_key": "dashboard.market", "value": 300},
                ],
                "metrics": {
                    "buy_count": 4,
                    "sell_count": 3,
                    "stop_loss_count": 1,
                    "realized_pnl": 12500.0,
                    "unrealized_pnl": -3200.0,
                    "recent_stop_loss_reason": "STOP_LOSS_PRICE_HIT",
                },
                "metric_items": [
                    {"key": "buy_count", "label": "Buy Count", "type": "count", "format_hint": "integer", "severity": "info", "state_message": 'Buy Count 4', "recommended_action": '현재 기록 흐름을 유지하며 모니터링하세요.', "recommended_action_label": 'MONITOR_ACTIVITY', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.executions", "value": 4},
                    {"key": "sell_count", "label": "Sell Count", "type": "count", "format_hint": "integer", "severity": "info", "state_message": 'Sell Count 3', "recommended_action": '현재 기록 흐름을 유지하며 모니터링하세요.', "recommended_action_label": 'MONITOR_ACTIVITY', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.executions", "value": 3},
                    {"key": "stop_loss_count", "label": "Stop Loss Count", "type": "count", "format_hint": "integer", "severity": "critical", "state_message": 'Stop Loss Count 1', "recommended_action": '최근 손절 흐름과 청산 원인을 점검하세요.', "recommended_action_label": 'REVIEW_STOP_LOSS', "action_group": 'review', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.positions.history", "value": 1},
                    {"key": "realized_pnl", "label": "Realized PnL", "type": "pnl", "format_hint": "signed_currency", "severity": "info", "state_message": 'Realized PnL 이익 12500.0', "recommended_action": '손익 흐름을 유지하며 모니터링하세요.', "recommended_action_label": 'MONITOR_PNL', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.executions", "value": 12500.0},
                    {"key": "unrealized_pnl", "label": "Unrealized PnL", "type": "pnl", "format_hint": "signed_currency", "severity": "warning", "state_message": 'Unrealized PnL 손실 -3200.0', "recommended_action": '손익 악화 원인과 리스크 설정을 점검하세요.', "recommended_action_label": 'REVIEW_PNL', "action_group": 'review', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.positions.current", "value": -3200.0},
                    {"key": "recent_stop_loss_reason", "label": "Recent Stop Loss Reason", "type": "text", "format_hint": "plain_text", "severity": "critical", "state_message": 'Recent Stop Loss Reason STOP_LOSS_PRICE_HIT', "recommended_action": '최근 손절 사유를 검토하고 재진입 조건을 점검하세요.', "recommended_action_label": 'REVIEW_STOP_LOSS_REASON', "action_group": 'review', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.positions.history", "value": "STOP_LOSS_PRICE_HIT"},
                ],
            },
            {
                "key": "learning",
                "name": "Learning",
                "state_label": "ACTIVE",
                "severity": "info",
                "state_message": "학습 이벤트 기록이 활성화되어 있습니다.",
                "recommended_action": "학습 로그 적재가 유지되는지만 주기적으로 확인하세요.",
                "updated_at": None,
                "stale": True,
                "age_sec": None,
                "freshness_state": "missing",
                "freshness_message": "데이터 없음",
                "freshness_label": "MISSING",
                "freshness_recommended_action": "데이터 소스와 수집 경로를 확인하세요.",
                "freshness_severity": "warning",
                "freshness_window_sec": 300,
                "freshness_metric_items": [
                    {"key": "updated_at", "label": "Updated At", "type": "timestamp", "state_message": 'Updated At 2026-04-19T20:00:01+09:00', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.learning", "value": "2026-04-19T20:00:01+09:00"},
                    {"key": "age_sec", "label": "Age Seconds", "type": "duration_sec", "state_message": 'Age Seconds 299', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.learning", "value": 299},
                    {"key": "freshness_window_sec", "label": "Freshness Window Seconds", "type": "window_sec", "state_message": 'Freshness Window Seconds 300', "recommended_action": 'freshness 기준 시간을 참고해 데이터 지연 여부를 판단하세요.', "recommended_action_label": 'REFERENCE_FRESHNESS_WINDOW', "action_group": 'reference', "action_priority": 'medium', "actionable": False, "action_url_key": "dashboard.learning", "value": 300},
                ],
                "metrics": {
                    "last_learning_event": None,
                    "learning_signal_count": 0,
                    "learning_fill_count": 0,
                    "last_signal_recorded_at": None,
                    "last_fill_recorded_at": None,
                },
                "metric_items": [
                    {"key": "last_learning_event", "label": "Last Learning Event", "type": "text", "format_hint": "plain_text", "severity": "info", "state_message": 'Last Learning Event 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.learning", "value": None},
                    {"key": "learning_signal_count", "label": "Signal Count", "type": "count", "format_hint": "integer", "severity": "info", "state_message": 'Signal Count 0', "recommended_action": '현재 기록 흐름을 유지하며 모니터링하세요.', "recommended_action_label": 'MONITOR_ACTIVITY', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.learning", "value": 0},
                    {"key": "learning_fill_count", "label": "Fill Count", "type": "count", "format_hint": "integer", "severity": "info", "state_message": 'Fill Count 0', "recommended_action": '현재 기록 흐름을 유지하며 모니터링하세요.', "recommended_action_label": 'MONITOR_ACTIVITY', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.learning", "value": 0},
                    {"key": "last_signal_recorded_at", "label": "Last Signal At", "type": "timestamp", "format_hint": "datetime", "severity": "info", "state_message": 'Last Signal At 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.learning", "value": None},
                    {"key": "last_fill_recorded_at", "label": "Last Fill At", "type": "timestamp", "format_hint": "datetime", "severity": "info", "state_message": 'Last Fill At 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.learning", "value": None},
                ],
            },
            {
                "key": "recovery",
                "name": "Recovery",
                "state_label": "HARD_STOP",
                "severity": "critical",
                "state_message": "하드스톱이 활성화되어 수동 개입이 필요합니다.",
                "recommended_action": "하드스톱 해제 전까지 수동 점검과 원인 분석을 진행하세요.",
                "updated_at": None,
                "stale": True,
                "age_sec": None,
                "freshness_state": "missing",
                "freshness_message": "데이터 없음",
                "freshness_label": "MISSING",
                "freshness_recommended_action": "데이터 소스와 수집 경로를 확인하세요.",
                "freshness_severity": "warning",
                "freshness_window_sec": 600,
                "freshness_metric_items": [
                    {"key": "updated_at", "label": "Updated At", "type": "timestamp", "state_message": 'Updated At 2026-04-19T20:00:04+09:00', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.recovery", "value": "2026-04-19T20:00:04+09:00"},
                    {"key": "age_sec", "label": "Age Seconds", "type": "duration_sec", "state_message": 'Age Seconds 296', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.recovery", "value": 296},
                    {"key": "freshness_window_sec", "label": "Freshness Window Seconds", "type": "window_sec", "state_message": 'Freshness Window Seconds 600', "recommended_action": 'freshness 기준 시간을 참고해 데이터 지연 여부를 판단하세요.', "recommended_action_label": 'REFERENCE_FRESHNESS_WINDOW', "action_group": 'reference', "action_priority": 'medium', "actionable": False, "action_url_key": "dashboard.recovery", "value": 600},
                ],
                "metrics": {
                    "safe_mode": True,
                    "hard_stop": True,
                    "trading_ready": False,
                    "failure_stage": "open_order_reconcile",
                    "last_restart_detected_at": None,
                    "last_recovery_completed_at": None,
                },
                "metric_items": [
                    {"key": "safe_mode", "label": "Safe Mode", "type": "boolean", "format_hint": "boolean_badge", "severity": "warning", "state_message": 'Safe Mode 활성', "recommended_action": 'SAFE_MODE 해제 전까지 원인 분석을 진행하세요.', "recommended_action_label": 'CHECK_SAFE_MODE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": True},
                    {"key": "hard_stop", "label": "Hard Stop", "type": "boolean", "format_hint": "boolean_badge", "severity": "critical", "state_message": 'Hard Stop 활성', "recommended_action": '하드스톱 해제 전까지 수동 점검과 원인 분석을 진행하세요.', "recommended_action_label": 'CHECK_HARD_STOP', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": True},
                    {"key": "trading_ready", "label": "Trading Ready", "type": "boolean", "format_hint": "boolean_badge", "severity": "warning", "state_message": 'Trading Ready 미준비', "recommended_action": '거래 준비 실패 원인을 점검하세요.', "recommended_action_label": 'CHECK_TRADING_READY', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": False},
                    {"key": "failure_stage", "label": "Failure Stage", "type": "text", "format_hint": "plain_text", "severity": "warning", "state_message": 'Failure Stage open_order_reconcile', "recommended_action": '실패 단계 원인을 확인하고 복구 절차를 점검하세요.', "recommended_action_label": 'CHECK_FAILURE_STAGE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": "open_order_reconcile"},
                    {"key": "last_restart_detected_at", "label": "Last Restart At", "type": "timestamp", "format_hint": "datetime", "severity": "info", "state_message": 'Last Restart At 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": None},
                    {"key": "last_recovery_completed_at", "label": "Last Recovery At", "type": "timestamp", "format_hint": "datetime", "severity": "info", "state_message": 'Last Recovery At 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": None},
                ],
            },
            {
                "key": "promotion",
                "name": "Promotion",
                "state_label": "NOT_READY",
                "severity": "warning",
                "state_message": "실거래 승격 검토 준비가 아직 완료되지 않았습니다.",
                "recommended_action": "승격 기준 미달 지표를 보완한 뒤 다시 검토하세요.",
                "updated_at": None,
                "stale": True,
                "age_sec": None,
                "freshness_state": "missing",
                "freshness_message": "데이터 없음",
                "freshness_label": "MISSING",
                "freshness_recommended_action": "데이터 소스와 수집 경로를 확인하세요.",
                "freshness_severity": "warning",
                "freshness_window_sec": 86400,
                "freshness_metric_items": [
                    {"key": "updated_at", "label": "Updated At", "type": "timestamp", "state_message": 'Updated At 2026-04-19T18:00:00+09:00', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.promotion", "value": "2026-04-19T18:00:00+09:00"},
                    {"key": "age_sec", "label": "Age Seconds", "type": "duration_sec", "state_message": 'Age Seconds 7200', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.promotion", "value": 7200},
                    {"key": "freshness_window_sec", "label": "Freshness Window Seconds", "type": "window_sec", "state_message": 'Freshness Window Seconds 86400', "recommended_action": 'freshness 기준 시간을 참고해 데이터 지연 여부를 판단하세요.', "recommended_action_label": 'REFERENCE_FRESHNESS_WINDOW', "action_group": 'reference', "action_priority": 'medium', "actionable": False, "action_url_key": "dashboard.promotion", "value": 86400},
                ],
                "metrics": {
                    "promotion_ready": False,
                    "last_promotion_reviewed_at": None,
                },
                "metric_items": [
                    {"key": "promotion_ready", "label": "Promotion Ready", "type": "boolean", "format_hint": "boolean_badge", "severity": "warning", "state_message": 'Promotion Ready 미준비', "recommended_action": '승격 기준 미달 항목을 보완하세요.', "recommended_action_label": 'IMPROVE_PROMOTION', "action_group": 'review', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.promotion", "value": False},
                    {"key": "last_promotion_reviewed_at", "label": "Last Promotion Review At", "type": "timestamp", "format_hint": "datetime", "severity": "info", "state_message": 'Last Promotion Review At 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.promotion", "value": None},
                ],
            },
        ],
        section_state_label={
            "trading": "STOP_LOSS_TRIGGERED",
            "learning": "ACTIVE",
            "recovery": "HARD_STOP",
            "promotion": "NOT_READY",
        },
        section_severity={
            "trading": "critical",
            "learning": "info",
            "recovery": "critical",
            "promotion": "warning",
        },
        section_state_message={
            "trading": "최근 손절 사유: STOP_LOSS_PRICE_HIT",
            "learning": "학습 이벤트 기록이 활성화되어 있습니다.",
            "recovery": "하드스톱이 활성화되어 수동 개입이 필요합니다.",
            "promotion": "실거래 승격 검토 준비가 아직 완료되지 않았습니다.",
        },
        section_recommended_action={
            "trading": "최근 손절 발생 원인과 청산 흐름을 점검하세요.",
            "learning": "학습 로그 적재가 유지되는지만 주기적으로 확인하세요.",
            "recovery": "하드스톱 해제 전까지 수동 점검과 원인 분석을 진행하세요.",
            "promotion": "승격 기준 미달 지표를 보완한 뒤 다시 검토하세요.",
        },
    )

    assert summary == DashboardSummary(
        coin_balance=180.5,
        cash_balance=250000.0,
        realized_pnl=12500.0,
        unrealized_pnl=-3200.0,
        buy_count=4,
        sell_count=3,
        stop_loss_count=1,
        recent_stop_loss_reason="STOP_LOSS_PRICE_HIT",
        trading_mode="demo",
        learning_enabled=True,
        last_learning_event=None,
        learning_signal_count=0,
        learning_fill_count=0,
        last_signal_recorded_at=None,
        last_fill_recorded_at=None,
        last_position_event=None,
        last_promotion_reviewed_at=None,
        last_restart_detected_at=None,
        last_recovery_completed_at=None,
        sections=[
            {
                "key": "trading",
                "name": "Trading",
                "state_label": "STOP_LOSS_TRIGGERED",
                "severity": "critical",
                "state_message": "최근 손절 사유: STOP_LOSS_PRICE_HIT",
                "recommended_action": "최근 손절 발생 원인과 청산 흐름을 점검하세요.",
                "updated_at": None,
                "stale": True,
                "age_sec": None,
                "freshness_state": "missing",
                "freshness_message": "데이터 없음",
                "freshness_label": "MISSING",
                "freshness_recommended_action": "데이터 소스와 수집 경로를 확인하세요.",
                "freshness_severity": "warning",
                "freshness_window_sec": 300,
                "freshness_metric_items": [
                    {"key": "updated_at", "label": "Updated At", "type": "timestamp", "state_message": 'Updated At 2026-04-19T20:00:01+09:00', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.market", "value": "2026-04-19T20:00:01+09:00"},
                    {"key": "age_sec", "label": "Age Seconds", "type": "duration_sec", "state_message": 'Age Seconds 299', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.market", "value": 299},
                    {"key": "freshness_window_sec", "label": "Freshness Window Seconds", "type": "window_sec", "state_message": 'Freshness Window Seconds 300', "recommended_action": 'freshness 기준 시간을 참고해 데이터 지연 여부를 판단하세요.', "recommended_action_label": 'REFERENCE_FRESHNESS_WINDOW', "action_group": 'reference', "action_priority": 'medium', "actionable": False, "action_url_key": "dashboard.market", "value": 300},
                ],
                "metrics": {
                    "buy_count": 4,
                    "sell_count": 3,
                    "stop_loss_count": 1,
                    "realized_pnl": 12500.0,
                    "unrealized_pnl": -3200.0,
                    "recent_stop_loss_reason": "STOP_LOSS_PRICE_HIT",
                },
                "metric_items": [
                    {"key": "buy_count", "label": "Buy Count", "type": "count", "format_hint": "integer", "severity": "info", "state_message": 'Buy Count 4', "recommended_action": '현재 기록 흐름을 유지하며 모니터링하세요.', "recommended_action_label": 'MONITOR_ACTIVITY', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.executions", "value": 4},
                    {"key": "sell_count", "label": "Sell Count", "type": "count", "format_hint": "integer", "severity": "info", "state_message": 'Sell Count 3', "recommended_action": '현재 기록 흐름을 유지하며 모니터링하세요.', "recommended_action_label": 'MONITOR_ACTIVITY', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.executions", "value": 3},
                    {"key": "stop_loss_count", "label": "Stop Loss Count", "type": "count", "format_hint": "integer", "severity": "critical", "state_message": 'Stop Loss Count 1', "recommended_action": '최근 손절 흐름과 청산 원인을 점검하세요.', "recommended_action_label": 'REVIEW_STOP_LOSS', "action_group": 'review', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.positions.history", "value": 1},
                    {"key": "realized_pnl", "label": "Realized PnL", "type": "pnl", "format_hint": "signed_currency", "severity": "info", "state_message": 'Realized PnL 이익 12500.0', "recommended_action": '손익 흐름을 유지하며 모니터링하세요.', "recommended_action_label": 'MONITOR_PNL', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.executions", "value": 12500.0},
                    {"key": "unrealized_pnl", "label": "Unrealized PnL", "type": "pnl", "format_hint": "signed_currency", "severity": "warning", "state_message": 'Unrealized PnL 손실 -3200.0', "recommended_action": '손익 악화 원인과 리스크 설정을 점검하세요.', "recommended_action_label": 'REVIEW_PNL', "action_group": 'review', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.positions.current", "value": -3200.0},
                    {"key": "recent_stop_loss_reason", "label": "Recent Stop Loss Reason", "type": "text", "format_hint": "plain_text", "severity": "critical", "state_message": 'Recent Stop Loss Reason STOP_LOSS_PRICE_HIT', "recommended_action": '최근 손절 사유를 검토하고 재진입 조건을 점검하세요.', "recommended_action_label": 'REVIEW_STOP_LOSS_REASON', "action_group": 'review', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.positions.history", "value": "STOP_LOSS_PRICE_HIT"},
                ],
            },
            {
                "key": "learning",
                "name": "Learning",
                "state_label": "ACTIVE",
                "severity": "info",
                "state_message": "학습 이벤트 기록이 활성화되어 있습니다.",
                "recommended_action": "학습 로그 적재가 유지되는지만 주기적으로 확인하세요.",
                "updated_at": None,
                "stale": True,
                "age_sec": None,
                "freshness_state": "missing",
                "freshness_message": "데이터 없음",
                "freshness_label": "MISSING",
                "freshness_recommended_action": "데이터 소스와 수집 경로를 확인하세요.",
                "freshness_severity": "warning",
                "freshness_window_sec": 300,
                "freshness_metric_items": [
                    {"key": "updated_at", "label": "Updated At", "type": "timestamp", "state_message": 'Updated At 2026-04-19T20:00:01+09:00', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.learning", "value": "2026-04-19T20:00:01+09:00"},
                    {"key": "age_sec", "label": "Age Seconds", "type": "duration_sec", "state_message": 'Age Seconds 299', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.learning", "value": 299},
                    {"key": "freshness_window_sec", "label": "Freshness Window Seconds", "type": "window_sec", "state_message": 'Freshness Window Seconds 300', "recommended_action": 'freshness 기준 시간을 참고해 데이터 지연 여부를 판단하세요.', "recommended_action_label": 'REFERENCE_FRESHNESS_WINDOW', "action_group": 'reference', "action_priority": 'medium', "actionable": False, "action_url_key": "dashboard.learning", "value": 300},
                ],
                "metrics": {
                    "last_learning_event": None,
                    "learning_signal_count": 0,
                    "learning_fill_count": 0,
                    "last_signal_recorded_at": None,
                    "last_fill_recorded_at": None,
                },
                "metric_items": [
                    {"key": "last_learning_event", "label": "Last Learning Event", "type": "text", "format_hint": "plain_text", "severity": "info", "state_message": 'Last Learning Event 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.learning", "value": None},
                    {"key": "learning_signal_count", "label": "Signal Count", "type": "count", "format_hint": "integer", "severity": "info", "state_message": 'Signal Count 0', "recommended_action": '현재 기록 흐름을 유지하며 모니터링하세요.', "recommended_action_label": 'MONITOR_ACTIVITY', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.learning", "value": 0},
                    {"key": "learning_fill_count", "label": "Fill Count", "type": "count", "format_hint": "integer", "severity": "info", "state_message": 'Fill Count 0', "recommended_action": '현재 기록 흐름을 유지하며 모니터링하세요.', "recommended_action_label": 'MONITOR_ACTIVITY', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.learning", "value": 0},
                    {"key": "last_signal_recorded_at", "label": "Last Signal At", "type": "timestamp", "format_hint": "datetime", "severity": "info", "state_message": 'Last Signal At 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.learning", "value": None},
                    {"key": "last_fill_recorded_at", "label": "Last Fill At", "type": "timestamp", "format_hint": "datetime", "severity": "info", "state_message": 'Last Fill At 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.learning", "value": None},
                ],
            },
            {
                "key": "recovery",
                "name": "Recovery",
                "state_label": "HARD_STOP",
                "severity": "critical",
                "state_message": "하드스톱이 활성화되어 수동 개입이 필요합니다.",
                "recommended_action": "하드스톱 해제 전까지 수동 점검과 원인 분석을 진행하세요.",
                "updated_at": None,
                "stale": True,
                "age_sec": None,
                "freshness_state": "missing",
                "freshness_message": "데이터 없음",
                "freshness_label": "MISSING",
                "freshness_recommended_action": "데이터 소스와 수집 경로를 확인하세요.",
                "freshness_severity": "warning",
                "freshness_window_sec": 600,
                "freshness_metric_items": [
                    {"key": "updated_at", "label": "Updated At", "type": "timestamp", "state_message": 'Updated At 2026-04-19T20:00:04+09:00', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.recovery", "value": "2026-04-19T20:00:04+09:00"},
                    {"key": "age_sec", "label": "Age Seconds", "type": "duration_sec", "state_message": 'Age Seconds 296', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.recovery", "value": 296},
                    {"key": "freshness_window_sec", "label": "Freshness Window Seconds", "type": "window_sec", "state_message": 'Freshness Window Seconds 600', "recommended_action": 'freshness 기준 시간을 참고해 데이터 지연 여부를 판단하세요.', "recommended_action_label": 'REFERENCE_FRESHNESS_WINDOW', "action_group": 'reference', "action_priority": 'medium', "actionable": False, "action_url_key": "dashboard.recovery", "value": 600},
                ],
                "metrics": {
                    "safe_mode": True,
                    "hard_stop": True,
                    "trading_ready": False,
                    "failure_stage": "open_order_reconcile",
                    "last_restart_detected_at": None,
                    "last_recovery_completed_at": None,
                },
                "metric_items": [
                    {"key": "safe_mode", "label": "Safe Mode", "type": "boolean", "format_hint": "boolean_badge", "severity": "warning", "state_message": 'Safe Mode 활성', "recommended_action": 'SAFE_MODE 해제 전까지 원인 분석을 진행하세요.', "recommended_action_label": 'CHECK_SAFE_MODE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": True},
                    {"key": "hard_stop", "label": "Hard Stop", "type": "boolean", "format_hint": "boolean_badge", "severity": "critical", "state_message": 'Hard Stop 활성', "recommended_action": '하드스톱 해제 전까지 수동 점검과 원인 분석을 진행하세요.', "recommended_action_label": 'CHECK_HARD_STOP', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": True},
                    {"key": "trading_ready", "label": "Trading Ready", "type": "boolean", "format_hint": "boolean_badge", "severity": "warning", "state_message": 'Trading Ready 미준비', "recommended_action": '거래 준비 실패 원인을 점검하세요.', "recommended_action_label": 'CHECK_TRADING_READY', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": False},
                    {"key": "failure_stage", "label": "Failure Stage", "type": "text", "format_hint": "plain_text", "severity": "warning", "state_message": 'Failure Stage open_order_reconcile', "recommended_action": '실패 단계 원인을 확인하고 복구 절차를 점검하세요.', "recommended_action_label": 'CHECK_FAILURE_STAGE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": "open_order_reconcile"},
                    {"key": "last_restart_detected_at", "label": "Last Restart At", "type": "timestamp", "format_hint": "datetime", "severity": "info", "state_message": 'Last Restart At 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": None},
                    {"key": "last_recovery_completed_at", "label": "Last Recovery At", "type": "timestamp", "format_hint": "datetime", "severity": "info", "state_message": 'Last Recovery At 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.recovery", "value": None},
                ],
            },
            {
                "key": "promotion",
                "name": "Promotion",
                "state_label": "NOT_READY",
                "severity": "warning",
                "state_message": "실거래 승격 검토 준비가 아직 완료되지 않았습니다.",
                "recommended_action": "승격 기준 미달 지표를 보완한 뒤 다시 검토하세요.",
                "updated_at": None,
                "stale": True,
                "age_sec": None,
                "freshness_state": "missing",
                "freshness_message": "데이터 없음",
                "freshness_label": "MISSING",
                "freshness_recommended_action": "데이터 소스와 수집 경로를 확인하세요.",
                "freshness_severity": "warning",
                "freshness_window_sec": 86400,
                "freshness_metric_items": [
                    {"key": "updated_at", "label": "Updated At", "type": "timestamp", "state_message": 'Updated At 2026-04-19T18:00:00+09:00', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.promotion", "value": "2026-04-19T18:00:00+09:00"},
                    {"key": "age_sec", "label": "Age Seconds", "type": "duration_sec", "state_message": 'Age Seconds 7200', "recommended_action": '최근 갱신 시각을 기준으로 데이터 freshness를 모니터링하세요.', "recommended_action_label": 'MONITOR_FRESHNESS', "action_group": 'monitor', "action_priority": 'low', "actionable": False, "action_url_key": "dashboard.promotion", "value": 7200},
                    {"key": "freshness_window_sec", "label": "Freshness Window Seconds", "type": "window_sec", "state_message": 'Freshness Window Seconds 86400', "recommended_action": 'freshness 기준 시간을 참고해 데이터 지연 여부를 판단하세요.', "recommended_action_label": 'REFERENCE_FRESHNESS_WINDOW', "action_group": 'reference', "action_priority": 'medium', "actionable": False, "action_url_key": "dashboard.promotion", "value": 86400},
                ],
                "metrics": {
                    "promotion_ready": False,
                    "last_promotion_reviewed_at": None,
                },
                "metric_items": [
                    {"key": "promotion_ready", "label": "Promotion Ready", "type": "boolean", "format_hint": "boolean_badge", "severity": "warning", "state_message": 'Promotion Ready 미준비', "recommended_action": '승격 기준 미달 항목을 보완하세요.', "recommended_action_label": 'IMPROVE_PROMOTION', "action_group": 'review', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.promotion", "value": False},
                    {"key": "last_promotion_reviewed_at", "label": "Last Promotion Review At", "type": "timestamp", "format_hint": "datetime", "severity": "info", "state_message": 'Last Promotion Review At 기록 없음', "recommended_action": '해당 기록 경로를 확인하세요.', "recommended_action_label": 'CHECK_ACTIVITY_SOURCE', "action_group": 'check', "action_priority": 'high', "actionable": True, "action_url_key": "dashboard.promotion", "value": None},
                ],
            },
        ],
        section_state_label={
            "trading": "STOP_LOSS_TRIGGERED",
            "learning": "ACTIVE",
            "recovery": "HARD_STOP",
            "promotion": "NOT_READY",
        },
        section_severity={
            "trading": "critical",
            "learning": "info",
            "recovery": "critical",
            "promotion": "warning",
        },
        section_state_message={
            "trading": "최근 손절 사유: STOP_LOSS_PRICE_HIT",
            "learning": "학습 이벤트 기록이 활성화되어 있습니다.",
            "recovery": "하드스톱이 활성화되어 수동 개입이 필요합니다.",
            "promotion": "실거래 승격 검토 준비가 아직 완료되지 않았습니다.",
        },
        section_recommended_action={
            "trading": "최근 손절 발생 원인과 청산 흐름을 점검하세요.",
            "learning": "학습 로그 적재가 유지되는지만 주기적으로 확인하세요.",
            "recovery": "하드스톱 해제 전까지 수동 점검과 원인 분석을 진행하세요.",
            "promotion": "승격 기준 미달 지표를 보완한 뒤 다시 검토하세요.",
        },
        safe_mode=True,
        hard_stop=True,
        trading_ready=False,
        promotion_ready=False,
    )
