from __future__ import annotations

from app.services.dashboard.summary import DashboardSummary, DashboardSummaryService
from app.services.portfolio.sync import PortfolioState
from app.services.recovery.orchestrator import BootState


def test_dashboard_summary_service_builds_summary_from_boot_state() -> None:
    service = DashboardSummaryService()
    boot_state = BootState(
        safe_mode=True,
        hard_stop=True,
        trading_ready=False,
        failure_stage="open_order_reconcile",
        portfolio_state=PortfolioState(
            cash_balance=250000.0,
            asset_currency="XRP",
            asset_balance=180.5,
            avg_buy_price=815.0,
        ),
        reconcile_result={"open_order_count": 2},
    )

    summary = service.build(
        boot_state=boot_state,
        trading_mode="demo",
        learning_enabled=True,
        realized_pnl=12500.0,
        unrealized_pnl=-3200.0,
        buy_count=4,
        sell_count=3,
        stop_loss_count=1,
        recent_stop_loss_reason="STOP_LOSS_PRICE_HIT",
        last_learning_event=None,
        learning_signal_count=0,
        learning_fill_count=0,
        last_signal_recorded_at=None,
        last_fill_recorded_at=None,
        last_position_event=None,
        last_promotion_reviewed_at=None,
        last_restart_detected_at=None,
        last_recovery_completed_at=None,
        promotion_ready=False,
        sections=[
            {
                "key": "trading",
                "name": "Trading",
                "state_label": "STOP_LOSS_TRIGGERED",
                "severity": "critical",
                "state_message": "최근 손절 사유: STOP_LOSS_PRICE_HIT",
                "recommended_action": "최근 손절 발생 원인과 청산 흐름을 점검하세요.",
                "metrics": {
                    "buy_count": 4,
                    "sell_count": 3,
                    "stop_loss_count": 1,
                    "realized_pnl": 12500.0,
                    "unrealized_pnl": -3200.0,
                    "recent_stop_loss_reason": "STOP_LOSS_PRICE_HIT",
                },
                "metric_items": [
                    {"key": "buy_count", "label": "Buy Count", "value": 4},
                    {"key": "sell_count", "label": "Sell Count", "value": 3},
                    {"key": "stop_loss_count", "label": "Stop Loss Count", "value": 1},
                    {"key": "realized_pnl", "label": "Realized PnL", "value": 12500.0},
                    {"key": "unrealized_pnl", "label": "Unrealized PnL", "value": -3200.0},
                    {"key": "recent_stop_loss_reason", "label": "Recent Stop Loss Reason", "value": "STOP_LOSS_PRICE_HIT"},
                ],
            },
            {
                "key": "learning",
                "name": "Learning",
                "state_label": "ACTIVE",
                "severity": "info",
                "state_message": "학습 이벤트 기록이 활성화되어 있습니다.",
                "recommended_action": "학습 로그 적재가 유지되는지만 주기적으로 확인하세요.",
                "metrics": {
                    "last_learning_event": None,
                    "learning_signal_count": 0,
                    "learning_fill_count": 0,
                    "last_signal_recorded_at": None,
                    "last_fill_recorded_at": None,
                },
                "metric_items": [
                    {"key": "last_learning_event", "label": "Last Learning Event", "value": None},
                    {"key": "learning_signal_count", "label": "Signal Count", "value": 0},
                    {"key": "learning_fill_count", "label": "Fill Count", "value": 0},
                    {"key": "last_signal_recorded_at", "label": "Last Signal At", "value": None},
                    {"key": "last_fill_recorded_at", "label": "Last Fill At", "value": None},
                ],
            },
            {
                "key": "recovery",
                "name": "Recovery",
                "state_label": "HARD_STOP",
                "severity": "critical",
                "state_message": "하드스톱이 활성화되어 수동 개입이 필요합니다.",
                "recommended_action": "하드스톱 해제 전까지 수동 점검과 원인 분석을 진행하세요.",
                "metrics": {
                    "safe_mode": True,
                    "hard_stop": True,
                    "trading_ready": False,
                    "failure_stage": "open_order_reconcile",
                    "last_restart_detected_at": None,
                    "last_recovery_completed_at": None,
                },
                "metric_items": [
                    {"key": "safe_mode", "label": "Safe Mode", "value": True},
                    {"key": "hard_stop", "label": "Hard Stop", "value": True},
                    {"key": "trading_ready", "label": "Trading Ready", "value": False},
                    {"key": "failure_stage", "label": "Failure Stage", "value": "open_order_reconcile"},
                    {"key": "last_restart_detected_at", "label": "Last Restart At", "value": None},
                    {"key": "last_recovery_completed_at", "label": "Last Recovery At", "value": None},
                ],
            },
            {
                "key": "promotion",
                "name": "Promotion",
                "state_label": "NOT_READY",
                "severity": "warning",
                "state_message": "실거래 승격 검토 준비가 아직 완료되지 않았습니다.",
                "recommended_action": "승격 기준 미달 지표를 보완한 뒤 다시 검토하세요.",
                "metrics": {
                    "promotion_ready": False,
                    "last_promotion_reviewed_at": None,
                },
                "metric_items": [
                    {"key": "promotion_ready", "label": "Promotion Ready", "value": False},
                    {"key": "last_promotion_reviewed_at", "label": "Last Promotion Review At", "value": None},
                ],
            },
        ],
        section_state_label={
            "trading": "STOP_LOSS_TRIGGERED",
            "learning": "ACTIVE",
            "recovery": "HARD_STOP",
            "promotion": "NOT_READY",
        },
        section_severity={
            "trading": "critical",
            "learning": "info",
            "recovery": "critical",
            "promotion": "warning",
        },
        section_state_message={
            "trading": "최근 손절 사유: STOP_LOSS_PRICE_HIT",
            "learning": "학습 이벤트 기록이 활성화되어 있습니다.",
            "recovery": "하드스톱이 활성화되어 수동 개입이 필요합니다.",
            "promotion": "실거래 승격 검토 준비가 아직 완료되지 않았습니다.",
        },
        section_recommended_action={
            "trading": "최근 손절 발생 원인과 청산 흐름을 점검하세요.",
            "learning": "학습 로그 적재가 유지되는지만 주기적으로 확인하세요.",
            "recovery": "하드스톱 해제 전까지 수동 점검과 원인 분석을 진행하세요.",
            "promotion": "승격 기준 미달 지표를 보완한 뒤 다시 검토하세요.",
        },
    )

    assert summary == DashboardSummary(
        coin_balance=180.5,
        cash_balance=250000.0,
        realized_pnl=12500.0,
        unrealized_pnl=-3200.0,
        buy_count=4,
        sell_count=3,
        stop_loss_count=1,
        recent_stop_loss_reason="STOP_LOSS_PRICE_HIT",
        trading_mode="demo",
        learning_enabled=True,
        last_learning_event=None,
        learning_signal_count=0,
        learning_fill_count=0,
        last_signal_recorded_at=None,
        last_fill_recorded_at=None,
        last_position_event=None,
        last_promotion_reviewed_at=None,
        last_restart_detected_at=None,
        last_recovery_completed_at=None,
        sections=[
            {
                "key": "trading",
                "name": "Trading",
                "state_label": "STOP_LOSS_TRIGGERED",
                "severity": "critical",
                "state_message": "최근 손절 사유: STOP_LOSS_PRICE_HIT",
                "recommended_action": "최근 손절 발생 원인과 청산 흐름을 점검하세요.",
                "metrics": {
                    "buy_count": 4,
                    "sell_count": 3,
                    "stop_loss_count": 1,
                    "realized_pnl": 12500.0,
                    "unrealized_pnl": -3200.0,
                    "recent_stop_loss_reason": "STOP_LOSS_PRICE_HIT",
                },
                "metric_items": [
                    {"key": "buy_count", "label": "Buy Count", "value": 4},
                    {"key": "sell_count", "label": "Sell Count", "value": 3},
                    {"key": "stop_loss_count", "label": "Stop Loss Count", "value": 1},
                    {"key": "realized_pnl", "label": "Realized PnL", "value": 12500.0},
                    {"key": "unrealized_pnl", "label": "Unrealized PnL", "value": -3200.0},
                    {"key": "recent_stop_loss_reason", "label": "Recent Stop Loss Reason", "value": "STOP_LOSS_PRICE_HIT"},
                ],
            },
            {
                "key": "learning",
                "name": "Learning",
                "state_label": "ACTIVE",
                "severity": "info",
                "state_message": "학습 이벤트 기록이 활성화되어 있습니다.",
                "recommended_action": "학습 로그 적재가 유지되는지만 주기적으로 확인하세요.",
                "metrics": {
                    "last_learning_event": None,
                    "learning_signal_count": 0,
                    "learning_fill_count": 0,
                    "last_signal_recorded_at": None,
                    "last_fill_recorded_at": None,
                },
                "metric_items": [
                    {"key": "last_learning_event", "label": "Last Learning Event", "value": None},
                    {"key": "learning_signal_count", "label": "Signal Count", "value": 0},
                    {"key": "learning_fill_count", "label": "Fill Count", "value": 0},
                    {"key": "last_signal_recorded_at", "label": "Last Signal At", "value": None},
                    {"key": "last_fill_recorded_at", "label": "Last Fill At", "value": None},
                ],
            },
            {
                "key": "recovery",
                "name": "Recovery",
                "state_label": "HARD_STOP",
                "severity": "critical",
                "state_message": "하드스톱이 활성화되어 수동 개입이 필요합니다.",
                "recommended_action": "하드스톱 해제 전까지 수동 점검과 원인 분석을 진행하세요.",
                "metrics": {
                    "safe_mode": True,
                    "hard_stop": True,
                    "trading_ready": False,
                    "failure_stage": "open_order_reconcile",
                    "last_restart_detected_at": None,
                    "last_recovery_completed_at": None,
                },
                "metric_items": [
                    {"key": "safe_mode", "label": "Safe Mode", "value": True},
                    {"key": "hard_stop", "label": "Hard Stop", "value": True},
                    {"key": "trading_ready", "label": "Trading Ready", "value": False},
                    {"key": "failure_stage", "label": "Failure Stage", "value": "open_order_reconcile"},
                    {"key": "last_restart_detected_at", "label": "Last Restart At", "value": None},
                    {"key": "last_recovery_completed_at", "label": "Last Recovery At", "value": None},
                ],
            },
            {
                "key": "promotion",
                "name": "Promotion",
                "state_label": "NOT_READY",
                "severity": "warning",
                "state_message": "실거래 승격 검토 준비가 아직 완료되지 않았습니다.",
                "recommended_action": "승격 기준 미달 지표를 보완한 뒤 다시 검토하세요.",
                "metrics": {
                    "promotion_ready": False,
                    "last_promotion_reviewed_at": None,
                },
                "metric_items": [
                    {"key": "promotion_ready", "label": "Promotion Ready", "value": False},
                    {"key": "last_promotion_reviewed_at", "label": "Last Promotion Review At", "value": None},
                ],
            },
        ],
        section_state_label={
            "trading": "STOP_LOSS_TRIGGERED",
            "learning": "ACTIVE",
            "recovery": "HARD_STOP",
            "promotion": "NOT_READY",
        },
        section_severity={
            "trading": "critical",
            "learning": "info",
            "recovery": "critical",
            "promotion": "warning",
        },
        section_state_message={
            "trading": "최근 손절 사유: STOP_LOSS_PRICE_HIT",
            "learning": "학습 이벤트 기록이 활성화되어 있습니다.",
            "recovery": "하드스톱이 활성화되어 수동 개입이 필요합니다.",
            "promotion": "실거래 승격 검토 준비가 아직 완료되지 않았습니다.",
        },
        section_recommended_action={
            "trading": "최근 손절 발생 원인과 청산 흐름을 점검하세요.",
            "learning": "학습 로그 적재가 유지되는지만 주기적으로 확인하세요.",
            "recovery": "하드스톱 해제 전까지 수동 점검과 원인 분석을 진행하세요.",
            "promotion": "승격 기준 미달 지표를 보완한 뒤 다시 검토하세요.",
        },
        safe_mode=True,
        hard_stop=True,
        trading_ready=False,
        promotion_ready=False,
    )
